__title__ = 'monchickey'
__description__ = 'Python 3 commonly used tool library'
__url__ = 'https://github.com/zengzhiying/py3monchickey/'
__version__ = '1.0.1'
__build__ = 0x010001
__author__ = 'zengzhiying'
__author_email__ = 'yingzhi_zeng@126.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2018 zengzhiying'
